---
name: mything

instance_groups:
- name: mything
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: mything
    release: mything
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: mything
  version: 1.0.0
  url: https://github.com/cloudfoundry-community/mything-boshrelease/releases/download/v1.0.0/mything-1.0.0.tgz
  sha1: a541e013320fce7cc47832adb616a0ed8334abb3
